### PR TITLE
Completed the exercise- Mohamed 

### PR DESCRIPTION
**Pull request by Mohamed-Elmessiry**
Screen Shot 2021-03-13 at 2 08 47 PM

### CODE REVIEW

**Comment by Mohamed-Elmessiry** [comment]
Screen Shot 2021-03-13 at 9 22 07 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Nice work so far!! The images have the rounded border cutting off the edge of the images, though. Please revise this to make the full image visible, as in the example. I suggest placing the image in a `div` container, and rounding the edges on that div, not the image itself. Additionally, the images should be in a perfect circle, whereas yours is an oval.

**Comment by Mohamed-Elmessiry** [comment]
Hi Cody, Just to clarify, as the photos are already in a div, do you mean two div parents instead of one ?

**Comment by Mohamed-Elmessiry** [comment]
Screen Shot 2021-03-16 at 12 07 43 PM

**Review by codingcodymiller — APPROVED** [review]
Nice work, dude!!

**Pull request merged**
